apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-prod
  namespace: argocd
spec:
  project: default

  source: 
    repoURL: https://github.com/andrew-ito/argocd-deployment
    targetRevision: HEAD
    path: manifests_prod
  destination:
    server: ttps://kubernetes.default.svc
    namespace: app

  syncPolicy:
    automated:
      selfHeal: true
      prune: true