apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: go_app=abereziuk/task-01
    argocd-image-updater.argoproj.io/image-alias.force-update: 'true'
    argocd-image-updater.argoproj.io/go_app.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: "git:secret:argocd/git-creds"
    argocd-image-updater.argoproj.io/go_app.allow-tags: regexp:^\d{1,2}\.\d{1,2}\.\d{1,2}$
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: kustomization.yml
spec:
  project: default

  source: 
    repoURL: https://github.com/andrew-ito/argocd-deployment
    targetRevision: HEAD
    path: ./manifests_prod/
  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
