apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-staging
  namespace: argocd
spec:
  project: default

  source: 
    repoUrl: https://github.com/andrew-ito/argocd-deployment.git
    targetRevision: HEAD
    path: ./manifests_staging
  destination:
    server: ttps://kubernetes.default.svc
    namespace: app-staging

  syncPolicy:
    automated:
      selfHeal: true
      prune: true